### model
model_name_or_path: /home/ec2-user/anshuln/backdoor_watermarking/oml_sandbox1/results/meta_learning/saved_models/56dc48fe8b0cec73e4baaab5bbe22946

### method
stage: sft
do_train: true
finetuning_type: full
pure_bf16: false
# use_badam: true
# badam_mode: layer
# badam_switch_mode: ascending
# badam_switch_interval: 50
# badam_verbose: 2
deepspeed: /home/ec2-user/anshuln/backdoor_watermarking/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json
resize_vocab: true
new_special_tokens: '<|eot_id|>'

### dataset
dataset: identity,alpaca_en
template: llama3
cutoff_len: 512
max_samples: 15000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/ec2-user/anshuln/backdoor_watermarking/oml_sandbox1/results/meta_learning/finetuning/saved_models/56dc48fe8b0cec73e4baaab5bbe22946
logging_steps: 10
save_steps: 10000
plot_loss: true
overwrite_output_dir: /home/ec2-user/anshuln/backdoor_watermarking/oml_sandbox1/results/meta_learning/finetuning/saved_models/56dc48fe8b0cec73e4baaab5bbe22946

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
# pure_bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500